[package]
name = "rust-knapsack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
itertools = { version = "0.10.3" }
snowflake = "1.2"